import type { TgHandlerContext } from '../types.js';
import { registerLoginCommand } from './login.js';
import { registerTopicCommand } from './topic.js';
import { registerRecallCommand } from './recall.js';
import { registerSearchCommand } from './search.js';
import { registerAddgroupCommand } from './addgroup.js';
import { registerAddfriendCommand } from './addfriend.js';
import { registerFriendrequestsCommand } from './friendrequests.js';
import { registerJoingroupCommand } from './joingroup.js';
import { registerLeavegroupCommand } from './leavegroup.js';
import { registerStatusCommand } from './status.js';
import { registerMenuCommand } from './menu.js';
import { registerSettingsCommand } from './settings.js';
import { registerHelpCommand } from './help.js';
import { registerBackupCommands } from './backup.js';
import { registerKickCommand, registerMembersCommand } from './members.js';
import { registerQueueCommand } from './queue.js';
import { registerClearCommand } from './clear.js';
import { registerAutoReplyCommand } from './autoreply.js';
import { registerGroupInfoCommands } from './group-info.js';
import { registerHistoryCommand } from './history.js';
import { registerSeedCommand } from './seed.js';
import { registerAdminCommand } from './admin.js';
import { registerUpdateCommand } from './update.js';
import { registerRestartCommand } from './restart.js';

export function registerAllCommands(ctx: TgHandlerContext): void {
  registerMenuCommand(ctx);
  registerHelpCommand(ctx);
  registerSettingsCommand(ctx);
  registerLoginCommand(ctx);
  registerTopicCommand(ctx);
  registerRecallCommand(ctx);
  registerSearchCommand(ctx);
  registerAddgroupCommand(ctx);
  registerAddfriendCommand(ctx);
  registerFriendrequestsCommand(ctx);
  registerJoingroupCommand(ctx);
  registerLeavegroupCommand(ctx);
  registerStatusCommand(ctx);
  registerBackupCommands(ctx);
  registerMembersCommand(ctx);
  registerKickCommand(ctx);
  registerQueueCommand(ctx);
  registerClearCommand(ctx);
  registerAutoReplyCommand(ctx);
  registerGroupInfoCommands(ctx);
  registerHistoryCommand(ctx);
  registerSeedCommand(ctx);
  registerAdminCommand(ctx);
  registerUpdateCommand(ctx);
  registerRestartCommand(ctx);
}
